name: python CI 

on: 
  push: 
    branches: [ "main" ]

jobs: 

    build: 
      runs-on: ubuntu-latest 

      steps: 
      - uses: actions/checkout@v3
      - name: Setup python 3.10 
        uses: actions/setup-python@v3
      - run: pip install -r requirements.txt
      - run: python test_main.py
      - uses: johnbeynon/render-deploy-action@v0.0.8
        with: 
          api-key: rnd_92bD3iFPFqrKzCB1rLO6Pt9amJHI
          app_name: pythonCI-CD
          
      